language: java

sudo: false # faster builds

jdk:
 - oraclejdk8

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: easy-buying

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
