version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=easy_buying
     - POSTGRES_USER=easy
     - POSTGRES_PASSWORD=buying
     - MAX_CONNECTIONS=300
 stubby4j:
   image: sandokandias/stubby4j-docker
   ports:
     - "8883:8883"
   environment:
     STUBBY_PORT: 8883
   volumes:
     - ./src/test/resources/stubby4j/stubby.yml:/usr/local/stubby.yml
