# APPLICATION
spring:
  application:
    name: Easy Buying
    description: A project developed by UNA students and coordinated by @bbranquinho.
    version: @project.version@
  profiles:
    active: dev

# SERVER
server:
  contextPath: /
  port: 8080
