# LOGGING
logging:
  file: build/easy-buying.log
  level:
    org.wpattern.easy.buying: INFO
    org.springframework: WARN
    org.hibernate: WARN

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
